def dividir(a, b):
    try:
        resultado = a / b
        res = resultado
    except ZeroDivisionError as e:
    #except Exception as e:
        print(f"Error en dividir: {e}")  # Imprime el error
        raise      # Re-lanza la excepci贸n
        #raise  e  
    return res

def main():
    try:
        resultado = dividir(10, 0)
        print(f"Resultado: {resultado}")
    except ZeroDivisionError:
        print("La operaci贸n de divisi贸n fall贸.")
main()
